# Generated by Django 4.2.7 on 2024-04-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_form_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_category',
            name='Image',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
