# Generated by Django 4.2.7 on 2024-04-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_form_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.IntegerField()),
                ('Sub_Category', models.IntegerField()),
                ('Image', models.ImageField(upload_to='media/')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
