# Generated by Django 5.0.4 on 2024-04-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='User_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
