# Generated by Django 5.0.4 on 2024-04-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_cart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
