# Generated by Django 5.0.4 on 2024-04-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Image',
            field=models.CharField(max_length=255),
        ),
    ]
