# Generated by Django 5.0.4 on 2024-04-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_cart_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='product_cart',
        ),
    ]
