# Generated by Django 5.0.4 on 2024-04-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_rename_cart_product_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=255)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
