# Generated by Django 5.0.3 on 2024-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_product_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_wishlist',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='product_wishlist',
            name='Stock',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
